version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-taf7gjzp1b6i"
s3_prefix = "sam"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "CognitoUserEmail=\"wilmar.cabezas@gmail.com\" APIStageName=\"prod\""
